name: CI


on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 

jobs:

  build:

     runs-on: ubuntu-latest


     steps:
    
        - uses: actions/checkout@v2
    
        - name: Compile   
          run: |
             echo "Hello Test"           
  
  Deploy:
      
       name: Deploy to stage
       if: github.event_name == 'pull_request'
       needs: [build]
      
       runs-on: ubuntu-latest
       environment: 
         name: Test
      
       steps:
        
         - name: Deploy
         - run: I am deploying to Test
         
      
      
       
          
#      - name: Checkout dependent repo details
#        uses: actions/checkout@v1
#        with:
#           repository: Nikunjrupapara/Customercare
#           token: ${{ secrets.TEST_PAT }}
         
      #- name: Configure git
      #  env:
      #    TOKEN: ${{ secrets.TEST_PAT }}
      #  run: git clone https://${TOKEN}:x-oauth-basic@https://github.com/Nikunj2122/Customercare.git   
