name: CI


on:

  push:
    branches: [ main ]
 


#  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create Src folder    
        run: |
          mkdir src && ls -l
      - name: Configure git
        env:
          TOKEN: ${{ secrets.TEST_PAT }}
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"         
