name: CI


on:

  push:
    branches: [ main ]

jobs:

  build:

     runs-on: ubuntu-latest


     steps:
    
        - uses: actions/checkout@v2
    
        - name: Compile & Build   
          run: |
             echo "Hello Build is Ready"           
  
  DeployDev:
      
       name: Deploy to Dev
       needs: [build]
      
       runs-on: ubuntu-latest
       environment: 
         name: Dev
      
       steps:
        
         
         - name: Deploy to Test
           run: |
             echo "I am deploying to Test"
             
             
  DeployStage:

         name: Deploy to Stage
         needs: [build]
         
         runs-on: ubuntu-latest
         environment: 
             name: Stage
          
          
         steps:
        
         
         - name: Deploy to Stage
           run: |
             echo "I am deploying to Stage" 
         
         
             
             
         
      
      
       
          
#      - name: Checkout dependent repo details
#        uses: actions/checkout@v1
#        with:
#           repository: Nikunjrupapara/Customercare
#           token: ${{ secrets.TEST_PAT }}
         
      #- name: Configure git
      #  env:
      #    TOKEN: ${{ secrets.TEST_PAT }}
      #  run: git clone https://${TOKEN}:x-oauth-basic@https://github.com/Nikunj2122/Customercare.git   
